#!/bin/sh
# Docker entrypoint script
# Generates runtime configuration from environment variables

set -e

CONFIG_FILE="/usr/share/nginx/html/config.js"

# Generate config.js with runtime environment variables
# Only include variables that are explicitly set in the environment
cat > "$CONFIG_FILE" << 'HEADER'
// Runtime configuration - generated at container startup
// This file is automatically generated by docker-entrypoint.sh
// Do not edit manually
window.__EXCALIDRAW_CONFIG__ = {
HEADER

# Helper function to add a config value if the env var is set
add_config() {
  VAR_NAME="$1"
  eval VAR_VALUE="\$$VAR_NAME"
  if [ -n "$VAR_VALUE" ]; then
    # Escape special characters for JavaScript string
    ESCAPED_VALUE=$(printf '%s' "$VAR_VALUE" | sed 's/\\/\\\\/g; s/"/\\"/g; s/'"'"'/\\'"'"'/g')
    echo "  \"$VAR_NAME\": \"$ESCAPED_VALUE\"," >> "$CONFIG_FILE"
  fi
}

# Add all configurable environment variables
add_config "VITE_APP_BACKEND_V2_GET_URL"
add_config "VITE_APP_BACKEND_V2_POST_URL"
add_config "VITE_APP_LIBRARY_URL"
add_config "VITE_APP_LIBRARY_BACKEND"
add_config "VITE_APP_PLUS_LP"
add_config "VITE_APP_PLUS_APP"
add_config "VITE_APP_AI_BACKEND"
add_config "VITE_APP_WS_SERVER_URL"
add_config "VITE_APP_FIREBASE_CONFIG"
add_config "VITE_APP_PLUS_EXPORT_PUBLIC_KEY"
add_config "VITE_APP_PORTAL_URL"
add_config "VITE_APP_DISABLE_SENTRY"
add_config "VITE_APP_ENABLE_TRACKING"

# Close the config object
echo "};" >> "$CONFIG_FILE"

echo "Generated runtime configuration at $CONFIG_FILE"

# Execute the CMD (nginx)
exec "$@"
